analytics: {}
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0
  lightness: 0.486007
  rhythmicContrast: 0.258637
  saturation: 0.509328
cta: {}
layout_spectrum: 0.7566719747428435
name: vranimation
opengraph: {}
purpose: {}
typography_spectrum: 0.347014
